// Full department roster used by the highlight-section filter dropdown.
// Source: Figma spec for screen `WXK5AYB_rG` (Dropdown Phòng ban).
// Names are proper nouns / org codes — NOT translated across locales.
export const DEPARTMENTS = [
  "CTO",
  "SPD",
  "FCOV",
  "CEVC1",
  "CEVC2",
  "CEVC3",
  "CEVC4",
  "CEVEC",
  "STVC",
  "STVC - R&D",
  "STVC - R&D - DTR",
  "STVC - R&D - DPS",
  "STVC - R&D - AIR",
  "STVC - R&D - SDX",
  "STVC - EE",
  "STVC - Infra",
  "CEVC1 - DSV",
  "CEVC1 - DSV - UI/UX 1",
  "CEVC1 - DSV - UI/UX 2",
  "CEVC1 - AIE",
  "CEVC2 - CySS",
  "CEVC2 - System",
  "CEVEC - SAPD",
  "CEVEC - GSD",
  "FCOV - LRM",
  "FCOV - F&A",
  "FCOV - GA",
  "FCOV - ISO",
  "OPD",
  "OPDC - HRF",
  "OPDC - HRF - C&B",
  "OPDC - HRF - OD",
  "OPDC - HRF - TA",
  "OPDC - HRD",
  "OPDC - HRD - C&C",
  "OPDC - HRD - L&D",
  "OPDC - HRD - TI",
  "OPDC - HRD - HRBP",
  "GEU",
  "GEU - HUST",
  "GEU - DUT",
  "GEU - TM",
  "GEU - UET",
  "GEU - UIT",
  "PAO",
  "PAO - PEC",
  "PAO - PAO",
  "IAV",
  "CPV",
  "CPV - CGP",
  "BDV",
  "Infra",
] as const;

export type Department = (typeof DEPARTMENTS)[number];
